# Generated by Django 4.2.1 on 2023-07-11 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratting',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ratting', to='api.product'),
        ),
        migrations.AlterField(
            model_name='ratting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratting_bussiness', to=settings.AUTH_USER_MODEL),
        ),
    ]
