# Generated by Django 4.2.1 on 2023-07-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="business_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
