# Generated by Django 3.2.8 on 2023-07-24 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_options_businessprofile_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advertisements')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
