# Generated by Django 4.2.1 on 2023-07-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_business_name_businessprofile_businessname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='text',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='user',
        ),
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='subject',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
