# Generated by Django 3.2.8 on 2023-07-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_business_name_businessprofile_businessname'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_visited',
            field=models.BooleanField(default=False),
        ),
    ]
