# Generated by Django 4.2.1 on 2023-07-31 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_order_is_visited"),
        ("api", "0006_remove_contactus_text_remove_contactus_user_and_more"),
    ]

    operations = []
