# Generated by Django 3.2.8 on 2023-07-27 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_is_visited'),
        ('api', '0006_remove_contactus_text_remove_contactus_user_and_more'),
    ]

    operations = [
    ]
