# Generated by Django 4.2.1 on 2023-08-11 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_merge_20230731_1939"),
        ("api", "0008_alter_product_options"),
    ]

    operations = []
